project:
  type: default
  output-dir: _site

format:
  html:
    toc: true
    toc-depth: 2
    toc-title: "Contents"
    number-sections: true
    self-contained: true
    embed-resources: true
    theme:
      light: [default, styles.css]
    css: styles.css
    code-fold: true
    code-summary: "Show code"
    fig-width: 10
    fig-height: 6
    fig-format: svg
    title-block-banner: false

execute:
  freeze: false
  cache: false
  echo: false
  warning: false

knitr:
  opts_chunk:
    fig.align: center

metadata-files:
  - data/variables.yml
